/**
 * Fallback niche detection patterns used when AI is unavailable.
 * Each niche has URL patterns, content keywords, and page type indicators.
 */

export interface NichePattern {
  niche: string;
  subCategories: string[];
  urlPatterns: RegExp[];
  contentKeywords: string[];
  pageTypeIndicators: Record<string, number>; // pageType -> weight
  technologyIndicators: string[]; // technology names that suggest this niche
}

export const NICHE_PATTERNS: NichePattern[] = [
  {
    niche: 'e-commerce',
    subCategories: ['fashion', 'electronics', 'home-garden', 'food-beverage', 'general-retail'],
    urlPatterns: [
      /\/product[s]?\//i,
      /\/shop\//i,
      /\/store\//i,
      /\/cart/i,
      /\/checkout/i,
      /\/collection[s]?\//i,
      /\/categor(y|ies)\//i,
      /\/item[s]?\//i,
      /\/order/i,
      /\/wishlist/i,
    ],
    contentKeywords: [
      'add to cart', 'buy now', 'shop now', 'price', 'checkout',
      'shipping', 'delivery', 'in stock', 'out of stock', 'sku',
      'product', 'catalog', 'sale', 'discount', 'coupon', 'shopping cart',
      'free shipping', 'returns', 'size guide', 'quantity',
    ],
    pageTypeIndicators: {
      product: 5,
      checkout: 5,
      cart: 4,
      category: 3,
      collection: 3,
    },
    technologyIndicators: ['Shopify', 'WooCommerce', 'Magento', 'BigCommerce', 'PrestaShop'],
  },
  {
    niche: 'saas',
    subCategories: ['b2b-saas', 'b2c-saas', 'devtools', 'marketing-tools', 'productivity'],
    urlPatterns: [
      /\/pricing/i,
      /\/features/i,
      /\/integrations/i,
      /\/docs\//i,
      /\/documentation/i,
      /\/api\//i,
      /\/changelog/i,
      /\/signup/i,
      /\/register/i,
      /\/demo/i,
      /\/trial/i,
    ],
    contentKeywords: [
      'free trial', 'start free', 'pricing', 'per month', 'per year',
      'enterprise', 'integration', 'api', 'dashboard', 'analytics',
      'features', 'platform', 'solution', 'subscribe', 'plan',
      'demo', 'request demo', 'get started', 'sign up free',
    ],
    pageTypeIndicators: {
      pricing: 5,
      features: 4,
      integrations: 3,
      documentation: 3,
      changelog: 2,
    },
    technologyIndicators: ['Intercom', 'Drift', 'Stripe'],
  },
  {
    niche: 'lead-generation',
    subCategories: ['real-estate', 'legal', 'medical', 'consulting', 'agency', 'local-business'],
    urlPatterns: [
      /\/contact/i,
      /\/about/i,
      /\/services/i,
      /\/quote/i,
      /\/consultation/i,
      /\/appointment/i,
      /\/book/i,
      /\/schedule/i,
      /\/estimate/i,
      /\/request/i,
    ],
    contentKeywords: [
      'contact us', 'get a quote', 'free consultation', 'call us',
      'request a quote', 'schedule', 'appointment', 'book now',
      'our services', 'our team', 'about us', 'testimonials',
      'case studies', 'portfolio', 'clients', 'free estimate',
      'phone', 'email us', 'get in touch',
    ],
    pageTypeIndicators: {
      contact: 5,
      services: 4,
      about: 3,
      testimonials: 3,
      portfolio: 2,
    },
    technologyIndicators: ['Calendly', 'HubSpot', 'Typeform'],
  },
  {
    niche: 'content',
    subCategories: ['blog', 'news', 'media', 'education', 'publishing'],
    urlPatterns: [
      /\/blog\//i,
      /\/article[s]?\//i,
      /\/post[s]?\//i,
      /\/news\//i,
      /\/stories\//i,
      /\/podcast/i,
      /\/video[s]?\//i,
      /\/learn\//i,
      /\/resource[s]?\//i,
      /\/guide[s]?\//i,
    ],
    contentKeywords: [
      'read more', 'published', 'author', 'subscribe', 'newsletter',
      'blog', 'article', 'latest posts', 'trending', 'editor',
      'share', 'comment', 'category', 'tags', 'read time',
      'related articles', 'featured', 'popular posts',
    ],
    pageTypeIndicators: {
      blog: 5,
      article: 4,
      news: 4,
      resource: 3,
    },
    technologyIndicators: ['WordPress', 'Ghost', 'Medium'],
  },
  {
    niche: 'non-profit',
    subCategories: ['charity', 'education', 'health', 'environment', 'community'],
    urlPatterns: [
      /\/donate/i,
      /\/volunteer/i,
      /\/cause[s]?\//i,
      /\/mission/i,
      /\/impact/i,
      /\/campaign[s]?\//i,
    ],
    contentKeywords: [
      'donate', 'donation', 'volunteer', 'mission', 'impact',
      'cause', 'help', 'support', 'give', 'fundraise',
      'community', 'non-profit', 'nonprofit', 'charity',
    ],
    pageTypeIndicators: {
      donate: 5,
      volunteer: 4,
      mission: 3,
      impact: 3,
    },
    technologyIndicators: [],
  },
  {
    niche: 'education',
    subCategories: ['online-courses', 'e-learning', 'edtech', 'academy', 'training'],
    urlPatterns: [
      /\/course[s]?\//i,
      /\/lesson[s]?\//i,
      /\/module[s]?\//i,
      /\/learn\//i,
      /\/training/i,
      /\/workshop[s]?\//i,
      /\/webinar[s]?\//i,
      /\/tutorial[s]?\//i,
      /\/academy/i,
      /\/curriculum/i,
      /\/enroll/i,
      /\/certification/i,
    ],
    contentKeywords: [
      'course', 'learn', 'enroll', 'student', 'instructor',
      'lesson', 'module', 'certification', 'curriculum', 'training',
      'workshop', 'webinar', 'tutorial', 'academy', 'education',
      'online learning', 'e-learning', 'skill', 'program',
      'syllabus', 'enrollment', 'class', 'teaching',
    ],
    pageTypeIndicators: {
      documentation: 3,
      blog: 2,
    },
    technologyIndicators: ['Teachable', 'Thinkific', 'Kajabi', 'Moodle', 'Canvas'],
  },
  {
    niche: 'healthcare',
    subCategories: ['medical', 'dental', 'wellness', 'fitness', 'pharma', 'telehealth'],
    urlPatterns: [
      /\/doctor[s]?\//i,
      /\/provider[s]?\//i,
      /\/patient[s]?\//i,
      /\/appointment/i,
      /\/health/i,
      /\/wellness/i,
      /\/condition[s]?\//i,
      /\/treatment[s]?\//i,
      /\/specialt(y|ies)\//i,
    ],
    contentKeywords: [
      'doctor', 'patient', 'appointment', 'health', 'medical',
      'wellness', 'treatment', 'diagnosis', 'clinic', 'hospital',
      'healthcare', 'therapy', 'symptoms', 'prescription',
      'HIPAA', 'provider', 'care', 'dental', 'physician',
    ],
    pageTypeIndicators: {
      services: 4,
      contact: 3,
      about: 2,
    },
    technologyIndicators: [],
  },
  {
    niche: 'finance',
    subCategories: ['fintech', 'banking', 'insurance', 'investment', 'crypto'],
    urlPatterns: [
      /\/account[s]?\//i,
      /\/invest/i,
      /\/loan[s]?\//i,
      /\/mortgage/i,
      /\/insurance/i,
      /\/banking/i,
      /\/portfolio/i,
      /\/calculator/i,
      /\/rates/i,
    ],
    contentKeywords: [
      'investment', 'loan', 'mortgage', 'insurance', 'banking',
      'financial', 'portfolio', 'savings', 'credit', 'interest rate',
      'APR', 'APY', 'stock', 'fund', 'retirement', 'fintech',
      'payment', 'transaction', 'account', 'wealth',
    ],
    pageTypeIndicators: {
      pricing: 3,
      about: 2,
    },
    technologyIndicators: ['Plaid', 'Stripe'],
  },
  {
    niche: 'real-estate',
    subCategories: ['residential', 'commercial', 'property-management', 'rentals'],
    urlPatterns: [
      /\/propert(y|ies)\//i,
      /\/listing[s]?\//i,
      /\/home[s]?\//i,
      /\/rent/i,
      /\/agent[s]?\//i,
      /\/neighborhood/i,
      /\/mls/i,
      /\/open-house/i,
    ],
    contentKeywords: [
      'property', 'listing', 'real estate', 'home', 'apartment',
      'rent', 'buy', 'mortgage', 'agent', 'broker', 'MLS',
      'bedroom', 'bathroom', 'sqft', 'square feet', 'neighborhood',
      'open house', 'virtual tour', 'for sale', 'for rent',
    ],
    pageTypeIndicators: {
      about: 2,
      contact: 3,
    },
    technologyIndicators: ['Zillow', 'Realtor'],
  },
  {
    niche: 'travel',
    subCategories: ['hotels', 'flights', 'tours', 'vacation-rentals', 'tourism'],
    urlPatterns: [
      /\/destination[s]?\//i,
      /\/hotel[s]?\//i,
      /\/flight[s]?\//i,
      /\/booking/i,
      /\/tour[s]?\//i,
      /\/itinerar(y|ies)\//i,
      /\/resort[s]?\//i,
      /\/travel/i,
    ],
    contentKeywords: [
      'hotel', 'flight', 'booking', 'destination', 'travel',
      'vacation', 'resort', 'tour', 'itinerary', 'check-in',
      'check-out', 'room', 'guest', 'reservation', 'airport',
      'cruise', 'adventure', 'trip', 'excursion',
    ],
    pageTypeIndicators: {},
    technologyIndicators: ['Booking.com', 'TripAdvisor'],
  },
  {
    niche: 'marketplace',
    subCategories: ['b2b-marketplace', 'b2c-marketplace', 'freelance', 'service-marketplace'],
    urlPatterns: [
      /\/seller[s]?\//i,
      /\/vendor[s]?\//i,
      /\/marketplace/i,
      /\/listing[s]?\//i,
      /\/browse/i,
      /\/categor(y|ies)\//i,
    ],
    contentKeywords: [
      'seller', 'vendor', 'marketplace', 'listing', 'buyer',
      'browse', 'sell', 'commission', 'platform', 'merchant',
      'supplier', 'wholesale', 'bid', 'auction',
    ],
    pageTypeIndicators: {
      category: 4,
      product: 3,
    },
    technologyIndicators: [],
  },
  {
    niche: 'food-delivery',
    subCategories: ['restaurant', 'meal-delivery', 'grocery', 'catering'],
    urlPatterns: [
      /\/menu/i,
      /\/order/i,
      /\/delivery/i,
      /\/restaurant[s]?\//i,
      /\/food/i,
      /\/meal[s]?\//i,
      /\/catering/i,
    ],
    contentKeywords: [
      'menu', 'order online', 'delivery', 'restaurant', 'food',
      'meal', 'cuisine', 'takeout', 'dine-in', 'catering',
      'pickup', 'kitchen', 'chef', 'dish', 'recipe',
    ],
    pageTypeIndicators: {},
    technologyIndicators: ['DoorDash', 'UberEats', 'Grubhub'],
  },
  {
    niche: 'entertainment',
    subCategories: ['gaming', 'streaming', 'music', 'events', 'media'],
    urlPatterns: [
      /\/event[s]?\//i,
      /\/show[s]?\//i,
      /\/ticket[s]?\//i,
      /\/watch/i,
      /\/play/i,
      /\/game[s]?\//i,
      /\/stream/i,
      /\/concert[s]?\//i,
    ],
    contentKeywords: [
      'event', 'show', 'ticket', 'watch', 'play', 'game',
      'stream', 'concert', 'movie', 'series', 'episode',
      'entertainment', 'music', 'artist', 'performer',
      'venue', 'live', 'performance',
    ],
    pageTypeIndicators: {},
    technologyIndicators: ['Eventbrite', 'Ticketmaster'],
  },
];

/**
 * Available niches for user selection in the niche confirmation UI.
 */
export const AVAILABLE_NICHES = [
  'e-commerce',
  'saas',
  'lead-generation',
  'content',
  'non-profit',
  'marketplace',
  'education',
  'healthcare',
  'real-estate',
  'travel',
  'finance',
  'food-delivery',
  'entertainment',
  'other',
];
