import { TrackingType, TrackingTypeMetadata } from '@/types/tracking.types';

// Comprehensive tracking type metadata for UI
export const TRACKING_TYPE_METADATA: Record<TrackingType, TrackingTypeMetadata> = {
  // Basic Interactions
  [TrackingType.BUTTON_CLICK]: {
    type: TrackingType.BUTTON_CLICK,
    label: 'Button Click',
    description: 'Track clicks on specific buttons',
    category: 'basic',
    icon: 'MousePointerClick',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'button_click',
    supportsValue: false,
  },
  [TrackingType.LINK_CLICK]: {
    type: TrackingType.LINK_CLICK,
    label: 'Link Click',
    description: 'Track clicks on links',
    category: 'basic',
    icon: 'Link',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'link_click',
    supportsValue: false,
  },
  [TrackingType.PAGE_VIEW]: {
    type: TrackingType.PAGE_VIEW,
    label: 'Page View',
    description: 'Track views on specific pages',
    category: 'basic',
    icon: 'Eye',
    requiredFields: ['urlPattern'],
    optionalFields: [],
    defaultGA4EventName: 'page_view',
    supportsValue: false,
  },
  [TrackingType.ELEMENT_VISIBILITY]: {
    type: TrackingType.ELEMENT_VISIBILITY,
    label: 'Element Visibility',
    description: 'Track when an element becomes visible',
    category: 'basic',
    icon: 'EyeOff',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'element_visible',
    supportsValue: false,
  },

  // Forms
  [TrackingType.FORM_SUBMIT]: {
    type: TrackingType.FORM_SUBMIT,
    label: 'Form Submit',
    description: 'Track form submissions',
    category: 'forms',
    icon: 'FileCheck',
    requiredFields: ['selector'],
    optionalFields: ['config.trackFields', 'config.fieldsToTrack'],
    defaultGA4EventName: 'form_submit',
    supportsValue: false,
  },
  [TrackingType.FORM_START]: {
    type: TrackingType.FORM_START,
    label: 'Form Start',
    description: 'Track when users start filling a form',
    category: 'forms',
    icon: 'FileEdit',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'form_start',
    supportsValue: false,
  },
  [TrackingType.FORM_ABANDON]: {
    type: TrackingType.FORM_ABANDON,
    label: 'Form Abandonment',
    description: 'Track when users abandon a form',
    category: 'forms',
    icon: 'FileX',
    requiredFields: ['selector'],
    optionalFields: ['config.trackFields'],
    defaultGA4EventName: 'form_abandon',
    supportsValue: false,
  },

  // E-commerce
  [TrackingType.ADD_TO_CART]: {
    type: TrackingType.ADD_TO_CART,
    label: 'Add to Cart',
    description: 'Track when products are added to cart',
    category: 'ecommerce',
    icon: 'ShoppingCart',
    requiredFields: ['selector'],
    optionalFields: ['config.trackValue', 'config.trackProductDetails'],
    defaultGA4EventName: 'add_to_cart',
    supportsValue: true,
  },
  [TrackingType.REMOVE_FROM_CART]: {
    type: TrackingType.REMOVE_FROM_CART,
    label: 'Remove from Cart',
    description: 'Track when products are removed from cart',
    category: 'ecommerce',
    icon: 'ShoppingCartOff',
    requiredFields: ['selector'],
    optionalFields: ['config.trackProductDetails'],
    defaultGA4EventName: 'remove_from_cart',
    supportsValue: false,
  },
  [TrackingType.ADD_TO_WISHLIST]: {
    type: TrackingType.ADD_TO_WISHLIST,
    label: 'Add to Wishlist',
    description: 'Track when products are added to wishlist',
    category: 'ecommerce',
    icon: 'Heart',
    requiredFields: ['selector'],
    optionalFields: ['config.trackProductDetails'],
    defaultGA4EventName: 'add_to_wishlist',
    supportsValue: false,
  },
  [TrackingType.VIEW_CART]: {
    type: TrackingType.VIEW_CART,
    label: 'View Cart',
    description: 'Track when users view their cart',
    category: 'ecommerce',
    icon: 'ShoppingBag',
    requiredFields: ['urlPattern'],
    optionalFields: [],
    defaultGA4EventName: 'view_cart',
    supportsValue: false,
  },
  [TrackingType.CHECKOUT_START]: {
    type: TrackingType.CHECKOUT_START,
    label: 'Checkout Start',
    description: 'Track when users begin checkout',
    category: 'ecommerce',
    icon: 'CreditCard',
    requiredFields: ['urlPattern'],
    optionalFields: ['config.trackValue'],
    defaultGA4EventName: 'begin_checkout',
    supportsValue: true,
  },
  [TrackingType.CHECKOUT_STEP]: {
    type: TrackingType.CHECKOUT_STEP,
    label: 'Checkout Step',
    description: 'Track progress through checkout steps',
    category: 'ecommerce',
    icon: 'ListOrdered',
    requiredFields: ['urlPattern'],
    optionalFields: [],
    defaultGA4EventName: 'checkout_progress',
    supportsValue: false,
  },
  [TrackingType.PURCHASE]: {
    type: TrackingType.PURCHASE,
    label: 'Purchase Complete',
    description: 'Track completed purchases',
    category: 'ecommerce',
    icon: 'CheckCircle',
    requiredFields: ['urlPattern'],
    optionalFields: ['config.trackValue', 'config.currency'],
    defaultGA4EventName: 'purchase',
    supportsValue: true,
  },
  [TrackingType.PRODUCT_VIEW]: {
    type: TrackingType.PRODUCT_VIEW,
    label: 'Product View',
    description: 'Track product detail page views',
    category: 'ecommerce',
    icon: 'Package',
    requiredFields: ['urlPattern'],
    optionalFields: ['config.trackProductDetails'],
    defaultGA4EventName: 'view_item',
    supportsValue: false,
  },

  // Lead Generation
  [TrackingType.PHONE_CALL_CLICK]: {
    type: TrackingType.PHONE_CALL_CLICK,
    label: 'Phone Call Click',
    description: 'Track clicks on phone numbers',
    category: 'lead-gen',
    icon: 'Phone',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'phone_call_click',
    supportsValue: true,
  },
  [TrackingType.EMAIL_CLICK]: {
    type: TrackingType.EMAIL_CLICK,
    label: 'Email Click',
    description: 'Track clicks on email links',
    category: 'lead-gen',
    icon: 'Mail',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'email_click',
    supportsValue: true,
  },
  [TrackingType.DOWNLOAD]: {
    type: TrackingType.DOWNLOAD,
    label: 'Download',
    description: 'Track file downloads',
    category: 'lead-gen',
    icon: 'Download',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'file_download',
    supportsValue: false,
  },
  [TrackingType.DEMO_REQUEST]: {
    type: TrackingType.DEMO_REQUEST,
    label: 'Demo Request',
    description: 'Track demo/consultation requests',
    category: 'lead-gen',
    icon: 'Calendar',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'demo_request',
    supportsValue: true,
  },
  [TrackingType.SIGNUP]: {
    type: TrackingType.SIGNUP,
    label: 'Sign Up',
    description: 'Track user registrations',
    category: 'lead-gen',
    icon: 'UserPlus',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'sign_up',
    supportsValue: true,
  },

  // Engagement
  [TrackingType.SCROLL_DEPTH]: {
    type: TrackingType.SCROLL_DEPTH,
    label: 'Scroll Depth',
    description: 'Track when users scroll to a certain depth',
    category: 'engagement',
    icon: 'ArrowDown',
    requiredFields: ['urlPattern', 'config.scrollPercentage'],
    optionalFields: ['config.fireOnce'],
    defaultGA4EventName: 'scroll_depth',
    supportsValue: false,
  },
  [TrackingType.TIME_ON_PAGE]: {
    type: TrackingType.TIME_ON_PAGE,
    label: 'Time on Page',
    description: 'Track engagement time on pages',
    category: 'engagement',
    icon: 'Clock',
    requiredFields: ['urlPattern', 'config.timeSeconds'],
    optionalFields: ['config.fireOnce'],
    defaultGA4EventName: 'time_on_page',
    supportsValue: false,
  },
  [TrackingType.VIDEO_PLAY]: {
    type: TrackingType.VIDEO_PLAY,
    label: 'Video Play',
    description: 'Track video plays',
    category: 'engagement',
    icon: 'Play',
    requiredFields: ['selector'],
    optionalFields: ['config.trackMilestones', 'config.milestones'],
    defaultGA4EventName: 'video_start',
    supportsValue: false,
  },
  [TrackingType.VIDEO_COMPLETE]: {
    type: TrackingType.VIDEO_COMPLETE,
    label: 'Video Complete',
    description: 'Track completed video views',
    category: 'engagement',
    icon: 'CheckSquare',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'video_complete',
    supportsValue: false,
  },

  // Navigation & Search
  [TrackingType.SITE_SEARCH]: {
    type: TrackingType.SITE_SEARCH,
    label: 'Site Search',
    description: 'Track internal site searches',
    category: 'navigation',
    icon: 'Search',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'search',
    supportsValue: false,
  },
  [TrackingType.FILTER_USE]: {
    type: TrackingType.FILTER_USE,
    label: 'Filter Use',
    description: 'Track filter/sorting interactions',
    category: 'navigation',
    icon: 'Filter',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'filter_use',
    supportsValue: false,
  },
  [TrackingType.TAB_SWITCH]: {
    type: TrackingType.TAB_SWITCH,
    label: 'Tab Switch',
    description: 'Track tab switching',
    category: 'navigation',
    icon: 'Columns',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'tab_switch',
    supportsValue: false,
  },
  [TrackingType.ACCORDION_EXPAND]: {
    type: TrackingType.ACCORDION_EXPAND,
    label: 'Accordion Expand',
    description: 'Track accordion/dropdown expansions',
    category: 'navigation',
    icon: 'ChevronDown',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'accordion_expand',
    supportsValue: false,
  },
  [TrackingType.MODAL_OPEN]: {
    type: TrackingType.MODAL_OPEN,
    label: 'Modal Open',
    description: 'Track modal/popup opens',
    category: 'navigation',
    icon: 'Square',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'modal_open',
    supportsValue: false,
  },

  // Social & Sharing
  [TrackingType.SOCIAL_SHARE]: {
    type: TrackingType.SOCIAL_SHARE,
    label: 'Social Share',
    description: 'Track social media shares',
    category: 'social',
    icon: 'Share2',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'share',
    supportsValue: false,
  },
  [TrackingType.SOCIAL_CLICK]: {
    type: TrackingType.SOCIAL_CLICK,
    label: 'Social Click',
    description: 'Track social media icon clicks',
    category: 'social',
    icon: 'Users',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'social_click',
    supportsValue: false,
  },

  // Content
  [TrackingType.PDF_DOWNLOAD]: {
    type: TrackingType.PDF_DOWNLOAD,
    label: 'PDF Download',
    description: 'Track PDF downloads',
    category: 'content',
    icon: 'FileText',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'pdf_download',
    supportsValue: false,
  },
  [TrackingType.FILE_DOWNLOAD]: {
    type: TrackingType.FILE_DOWNLOAD,
    label: 'File Download',
    description: 'Track general file downloads',
    category: 'content',
    icon: 'File',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'file_download',
    supportsValue: false,
  },
  [TrackingType.NEWSLETTER_SIGNUP]: {
    type: TrackingType.NEWSLETTER_SIGNUP,
    label: 'Newsletter Signup',
    description: 'Track newsletter subscriptions',
    category: 'content',
    icon: 'Newspaper',
    requiredFields: ['selector'],
    optionalFields: [],
    defaultGA4EventName: 'newsletter_signup',
    supportsValue: false,
  },

  // Custom
  [TrackingType.CUSTOM_EVENT]: {
    type: TrackingType.CUSTOM_EVENT,
    label: 'Custom Event',
    description: 'Track custom events',
    category: 'custom',
    icon: 'Sparkles',
    requiredFields: ['selector'],
    optionalFields: ['ga4EventName'],
    defaultGA4EventName: 'custom_event',
    supportsValue: true,
  },
};

// Group tracking types by category
export const TRACKING_CATEGORIES = {
  basic: {
    label: 'Basic Interactions',
    types: [
      TrackingType.BUTTON_CLICK,
      TrackingType.LINK_CLICK,
      TrackingType.PAGE_VIEW,
      TrackingType.ELEMENT_VISIBILITY,
    ],
  },
  forms: {
    label: 'Forms',
    types: [TrackingType.FORM_SUBMIT, TrackingType.FORM_START, TrackingType.FORM_ABANDON],
  },
  ecommerce: {
    label: 'E-commerce',
    types: [
      TrackingType.ADD_TO_CART,
      TrackingType.REMOVE_FROM_CART,
      TrackingType.ADD_TO_WISHLIST,
      TrackingType.VIEW_CART,
      TrackingType.CHECKOUT_START,
      TrackingType.CHECKOUT_STEP,
      TrackingType.PURCHASE,
      TrackingType.PRODUCT_VIEW,
    ],
  },
  'lead-gen': {
    label: 'Lead Generation',
    types: [
      TrackingType.PHONE_CALL_CLICK,
      TrackingType.EMAIL_CLICK,
      TrackingType.DOWNLOAD,
      TrackingType.DEMO_REQUEST,
      TrackingType.SIGNUP,
    ],
  },
  engagement: {
    label: 'Engagement',
    types: [
      TrackingType.SCROLL_DEPTH,
      TrackingType.TIME_ON_PAGE,
      TrackingType.VIDEO_PLAY,
      TrackingType.VIDEO_COMPLETE,
    ],
  },
  navigation: {
    label: 'Navigation & Search',
    types: [
      TrackingType.SITE_SEARCH,
      TrackingType.FILTER_USE,
      TrackingType.TAB_SWITCH,
      TrackingType.ACCORDION_EXPAND,
      TrackingType.MODAL_OPEN,
    ],
  },
  social: {
    label: 'Social & Sharing',
    types: [TrackingType.SOCIAL_SHARE, TrackingType.SOCIAL_CLICK],
  },
  content: {
    label: 'Content',
    types: [
      TrackingType.PDF_DOWNLOAD,
      TrackingType.FILE_DOWNLOAD,
      TrackingType.NEWSLETTER_SIGNUP,
    ],
  },
  custom: {
    label: 'Custom',
    types: [TrackingType.CUSTOM_EVENT],
  },
};
